### ISSUE TITLE
Broken build

### ISSUE THREAD

**Issue by j-wilkie** [topse-agile/ucl-nii-misosoup#1]
I had the mockito test working but when I have merged with the latest version it has messed up for some reason. We might need to roll back the last few commits as none of the tests will run now on my system.

**Comment by hirura** [comment]
Would you mind pushing your latest codes with branching and replying to this comment with error messages so that we can check and merge tmr morning ?

**Comment by hirura** [comment]
Sorry, I found that the latest was already pushed into the repository.

Now I've fixed the issue. Please confirm that the latest works fine in your environment as well, and close this issue.

**Comment by j-wilkie** [comment]
Done, thank you.
